/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1210_2425_14a_nevek;

import java.io.File;
import java.util.Scanner;
import javax.swing.DefaultListModel;

/**
 *
 * @author wuncs.david
 */
public class frmNevek extends javax.swing.JFrame {

    DefaultListModel<Szemely> fiuk =
            new DefaultListModel<>();
    DefaultListModel<Szemely> lanyok =
            new DefaultListModel<>();
    public frmNevek() {
        initComponents();
        feltolt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblAvg = new javax.swing.JLabel();
        lblDb = new javax.swing.JLabel();
        rbLany = new javax.swing.JRadioButton();
        rbFiuk = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbNevek = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAvg.setText("lblAvg");

        lblDb.setText("lblDb");

        buttonGroup1.add(rbLany);
        rbLany.setText("Lányok");
        rbLany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLanyActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbFiuk);
        rbFiuk.setText("Fiúk");
        rbFiuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFiukActionPerformed(evt);
            }
        });

        lbNevek.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lbNevek);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvg)
                            .addComponent(lblDb)))
                    .addComponent(rbFiuk)
                    .addComponent(rbLany))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvg)
                        .addGap(18, 18, 18)
                        .addComponent(lblDb)
                        .addGap(23, 23, 23)
                        .addComponent(rbLany)
                        .addGap(18, 18, 18)
                        .addComponent(rbFiuk)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLanyActionPerformed
        lbNevek.setModel(lanyok);
        lblDb.setText("Darab: "+lanyok.size());
        lblAvg.setText(atlag(lanyok));
    }//GEN-LAST:event_rbLanyActionPerformed

    private void rbFiukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFiukActionPerformed
        lbNevek.setModel(fiuk);
        lblDb.setText("Darab: "+fiuk.size());
        lblAvg.setText(atlag(fiuk));
    }//GEN-LAST:event_rbFiukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNevek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNevek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNevek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNevek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNevek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lbNevek;
    private javax.swing.JLabel lblAvg;
    private javax.swing.JLabel lblDb;
    private javax.swing.JRadioButton rbFiuk;
    private javax.swing.JRadioButton rbLany;
    // End of variables declaration//GEN-END:variables

    private void feltolt() {
        File f = new File("nevek.csv");
        try {
            Scanner be = new Scanner(f,"UTF-8");
            String nev;
            String adatok [];
            be.nextLine();
            while(be.hasNextLine()){
                nev = be.nextLine();
                adatok = nev.split(";");
                if (adatok[2].equals("0")){
                    lanyok.addElement(
                    new Szemely(adatok[0],
                    Integer.parseInt(adatok[1]),
                    Integer.parseInt(adatok[2])));
                }
                else
                    fiuk.addElement(
                    new Szemely(adatok[0],
                    Integer.parseInt(adatok[1]),
                    Integer.parseInt(adatok[2])));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private String atlag(DefaultListModel<Szemely> lista) {
        double avg = 0;
        
        for (int i = 0; i < lista.size(); i++) {
            avg += lista.get(i).getKor();
        }
        
        avg /= lista.size();
        
        return String.format("Átlag: %.2f",avg);
        
    }

    
}
