/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1017_2324_14a;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author wuncs.david
 */
public class frmListBox extends javax.swing.JFrame {

    DefaultListModel<String> nevek 
            = new DefaultListModel<>();
    DefaultListModel<String> szurt 
            = new DefaultListModel<>();
    DefaultListModel<String> kedvencek 
            = new DefaultListModel<>();
    public frmListBox() {
        initComponents();
        lbNevek.setModel(nevek);
        lbSzurt.setModel(szurt);
        lbKedvencek.setModel(kedvencek);
        nevek.addElement("Lajos");
        nevek.addElement("Béla");
        for (int i = 0; i < 100; i++) {
            nevek.addElement("Név"+i);
        }
        nevek.remove(1);
        nevek.removeElement("Lajos");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lbNevek = new javax.swing.JList();
        lblIndex = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbSzurt = new javax.swing.JList();
        btnSzur = new javax.swing.JButton();
        btnVissza = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lbKedvencek = new javax.swing.JList();
        btnKedvenc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNevek.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lbNevek.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbNevekValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lbNevek);

        lblIndex.setText("jLabel1");

        lblValue.setText("jLabel1");

        lbSzurt.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lbSzurt);

        btnSzur.setText(">>");
        btnSzur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSzurActionPerformed(evt);
            }
        });

        btnVissza.setText("<<");
        btnVissza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisszaActionPerformed(evt);
            }
        });

        lbKedvencek.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lbKedvencek);

        btnKedvenc.setText("V");
        btnKedvenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKedvencActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblIndex)
                                .addGap(40, 40, 40)
                                .addComponent(lblValue))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSzur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVissza, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnKedvenc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIndex)
                            .addComponent(lblValue))
                        .addGap(43, 43, 43)
                        .addComponent(btnSzur)
                        .addGap(31, 31, 31)
                        .addComponent(btnVissza))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(btnKedvenc, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbNevekValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbNevekValueChanged
        lblIndex.setText(lbNevek.getSelectedIndex()+"");
        lblValue.setText(lbNevek.getSelectedValue()+"");
//        lblValue.setText(nevek.get(lbNevek.getSelectedIndex()));
        
    }//GEN-LAST:event_lbNevekValueChanged

    private void btnSzurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSzurActionPerformed
        if (lbNevek.getSelectedIndex() != -1){
            szurt.addElement(lbNevek.getSelectedValue()+"");
            nevek.remove(lbNevek.getSelectedIndex());
        }
        else{
            JOptionPane.showMessageDialog(
                this,"Nincs semmi kijelölve!");
        }
    }//GEN-LAST:event_btnSzurActionPerformed

    private void btnVisszaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisszaActionPerformed
        if (lbSzurt.getSelectedIndex() != -1){
            nevek.addElement(lbSzurt.getSelectedValue()+"");
            szurt.remove(lbSzurt.getSelectedIndex());
        }
        else{
            JOptionPane.showMessageDialog(
                this,"Nincs semmi kijelölve!");
        }
    }//GEN-LAST:event_btnVisszaActionPerformed

    private void btnKedvencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKedvencActionPerformed
        if (!kedvencek.contains(lbNevek.getSelectedValue()))
            kedvencek.addElement(lbNevek.getSelectedValue()+"");
        else
            JOptionPane.showMessageDialog(this,"Már benne van!");
    }//GEN-LAST:event_btnKedvencActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKedvenc;
    private javax.swing.JButton btnSzur;
    private javax.swing.JButton btnVissza;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lbKedvencek;
    private javax.swing.JList lbNevek;
    private javax.swing.JList lbSzurt;
    private javax.swing.JLabel lblIndex;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
