/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cukraszda;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Wuncs.David
 */
public class frmAlap extends javax.swing.JFrame {

    /**
     * Creates new form frmAlap
     */
    public frmAlap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mbMenu = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miMegnyit = new javax.swing.JMenuItem();
        mSuti = new javax.swing.JMenu();
        mNevjegy = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wuncs.David\\Desktop\\gasly.jpg")); // NOI18N

        mFile.setText("File");

        miMegnyit.setText("Megnyitás");
        miMegnyit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMegnyitActionPerformed(evt);
            }
        });
        mFile.add(miMegnyit);

        mbMenu.add(mFile);

        mSuti.setText("Sütemények");
        mSuti.setEnabled(false);
        mSuti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSutiMouseClicked(evt);
            }
        });
        mbMenu.add(mSuti);

        mNevjegy.setText("Névjegy");
        mbMenu.add(mNevjegy);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miMegnyitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMegnyitActionPerformed
      JFileChooser fcChooser = new JFileChooser();
      int re = fcChooser.showOpenDialog(this);
      if (re == JFileChooser.APPROVE_OPTION){
          String file = fcChooser.getSelectedFile().toString();
          feltolt(file);
          mSuti.setEnabled(true);
      }
    }//GEN-LAST:event_miMegnyitActionPerformed

    private void mSutiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSutiMouseClicked
        frmEtlap e = new frmEtlap();
        e.setVisible(true);
    }//GEN-LAST:event_mSutiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mNevjegy;
    private javax.swing.JMenu mSuti;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miMegnyit;
    // End of variables declaration//GEN-END:variables
    static ArrayList<Suti> sutik = new ArrayList<>();
    private void feltolt(String file) {
        File f = new File(file);
        try {
            Scanner be = new Scanner(f,"UTF-8");
            String sor;
            String [] adatok;
            while(be.hasNextLine()){
              sor = be.nextLine();
              adatok = sor.split(";");
              sutik.add(new Suti(adatok[0],
                      Integer.parseInt(adatok[1])));
            }
        } catch (FileNotFoundException ex) {
            System.out.println("Hiba");
        }
    }
}
