/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1128_2425_14a_jackie_graf;

import java.io.File;
import java.util.Scanner;
import javax.swing.DefaultListModel;

/**
 *
 * @author wuncs.david
 */
public class frmJackie extends javax.swing.JFrame {

    DefaultListModel<Jackie> eredmenyek =
            new DefaultListModel<>();
    public frmJackie() {
        initComponents();
        lbAdatok.setModel(eredmenyek);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lbAdatok = new javax.swing.JList();
        lblRaces = new javax.swing.JLabel();
        lblWins = new javax.swing.JLabel();
        lblPods = new javax.swing.JLabel();
        lblPoles = new javax.swing.JLabel();
        lblFastest = new javax.swing.JLabel();
        btnBeolvas = new javax.swing.JButton();
        btnF3 = new javax.swing.JButton();
        btnF4 = new javax.swing.JButton();
        btnF5 = new javax.swing.JButton();
        lblF3 = new javax.swing.JLabel();
        lblF4 = new javax.swing.JLabel();
        lblF5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbAdatok.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lbAdatok.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbAdatokValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lbAdatok);

        lblRaces.setText("jLabel1");

        lblWins.setText("jLabel1");

        lblPods.setText("jLabel1");

        lblPoles.setText("jLabel1");

        lblFastest.setText("jLabel1");

        btnBeolvas.setText("Beolvas");
        btnBeolvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeolvasActionPerformed(evt);
            }
        });

        btnF3.setText("3. feladat");
        btnF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF3ActionPerformed(evt);
            }
        });

        btnF4.setText("4. feladat");
        btnF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF4ActionPerformed(evt);
            }
        });

        btnF5.setText("5. feladat");
        btnF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF5ActionPerformed(evt);
            }
        });

        lblF3.setText("jLabel1");

        lblF4.setText("jLabel1");

        lblF5.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRaces, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWins, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPods, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPoles, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFastest, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnBeolvas))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnF5)
                                .addGap(18, 18, 18)
                                .addComponent(lblF5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnF4)
                                .addGap(18, 18, 18)
                                .addComponent(lblF4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnF3)
                                .addGap(18, 18, 18)
                                .addComponent(lblF3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRaces, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWins, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPods, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPoles, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFastest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBeolvas)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF3)
                    .addComponent(lblF3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF4)
                    .addComponent(lblF4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF5)
                    .addComponent(lblF5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeolvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeolvasActionPerformed
        if (eredmenyek.isEmpty())
            feltolt();
    }//GEN-LAST:event_btnBeolvasActionPerformed

    private void lbAdatokValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbAdatokValueChanged
        Jackie j = eredmenyek.get(lbAdatok.getSelectedIndex());
        lblFastest.setText("Leggyorsabb körök: "+j.getFastest());
        lblPods.setText("Dobogók: "+j.getPods());
        lblPoles.setText("Pole pozíciók: "+j.getPoles());
        lblRaces.setText("Futamok: "+j.getRaces());
        lblWins.setText("Győzelmek: "+j.getWins());
    }//GEN-LAST:event_lbAdatokValueChanged

    private void btnF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF3ActionPerformed
        lblF3.setText("3. feladat: "+eredmenyek.getSize());
    }//GEN-LAST:event_btnF3ActionPerformed
        Jackie max;
    private void btnF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF4ActionPerformed
        max = eredmenyek.get(0);
        for (int i = 0; i < eredmenyek.getSize(); i++) {
            if (eredmenyek.get(i).getRaces() > max.getRaces())
                max = eredmenyek.get(i);
        }
        lblF4.setText("4. Feladat: "+max.getYear());
        
    }//GEN-LAST:event_btnF4ActionPerformed
    int hat;
    int het;
    private void btnF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF5ActionPerformed
        hat = 0;
        het = 0;
        
        for (int i = 0; i < eredmenyek.getSize(); i++) {
            if (eredmenyek.get(i).getYear() < 1970)
                hat += eredmenyek.get(i).getWins();
            else
                het += eredmenyek.get(i).getWins();
        }
        lblF5.setText(String.format("<html> 60-as évek: %d <br> 70-es évek: %d",hat,het));
        
    }//GEN-LAST:event_btnF5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJackie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJackie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJackie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJackie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJackie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeolvas;
    private javax.swing.JButton btnF3;
    private javax.swing.JButton btnF4;
    private javax.swing.JButton btnF5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lbAdatok;
    private javax.swing.JLabel lblF3;
    private javax.swing.JLabel lblF4;
    private javax.swing.JLabel lblF5;
    private javax.swing.JLabel lblFastest;
    private javax.swing.JLabel lblPods;
    private javax.swing.JLabel lblPoles;
    private javax.swing.JLabel lblRaces;
    private javax.swing.JLabel lblWins;
    // End of variables declaration//GEN-END:variables

    private void feltolt() {
        File f = new File("jackie.txt");
        try {
            Scanner be = new Scanner(f,"UTF-8");
            be.nextLine();
            String [] adatok;
            String sor;
                                   
            while(be.hasNextLine()){
                sor = be.nextLine();
                adatok = sor.split("\t");
                eredmenyek.addElement(new Jackie(
                        Integer.parseInt(adatok[0]),
                        Integer.parseInt(adatok[1]),
                        Integer.parseInt(adatok[2]),
                        Integer.parseInt(adatok[3]),
                        Integer.parseInt(adatok[4]),
                        Integer.parseInt(adatok[5])));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
