/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bevezetes;

import javax.swing.JOptionPane;

/**
 *
 * @author wuncs.david
 */
public class Ismetles extends javax.swing.JFrame {

    /**
     * Creates new form Ismetles
     */
    public Ismetles() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGomb = new javax.swing.JButton();
        lblSzam = new javax.swing.JLabel();
        sldCsuszka = new javax.swing.JSlider();
        btnMsg1 = new javax.swing.JButton();
        btnMsg2 = new javax.swing.JButton();
        btnMsg3 = new javax.swing.JButton();
        btnMsg4 = new javax.swing.JButton();
        lblEredmeny = new javax.swing.JLabel();
        btnSzamol = new javax.swing.JButton();
        tfSzam = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGomb.setText("Klikk!");
        btnGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGombActionPerformed(evt);
            }
        });

        lblSzam.setText("Egy");

        sldCsuszka.setValue(100);
        sldCsuszka.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldCsuszkaStateChanged(evt);
            }
        });

        btnMsg1.setText("Alap popup");
        btnMsg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsg1ActionPerformed(evt);
            }
        });

        btnMsg2.setText("Warning");
        btnMsg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsg2ActionPerformed(evt);
            }
        });

        btnMsg3.setText("Error");
        btnMsg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsg3ActionPerformed(evt);
            }
        });

        btnMsg4.setText("Plain");
        btnMsg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsg4ActionPerformed(evt);
            }
        });

        lblEredmeny.setText("jLabel1");

        btnSzamol.setText("Számol");

        tfSzam.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(sldCsuszka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMsg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMsg2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMsg3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMsg4)))
                .addContainerGap(398, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(lblSzam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEredmeny)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnGomb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSzamol)))
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSzam)
                    .addComponent(lblEredmeny))
                .addGap(24, 24, 24)
                .addComponent(tfSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnGomb))
                    .addComponent(btnSzamol))
                .addGap(53, 53, 53)
                .addComponent(sldCsuszka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMsg1)
                    .addComponent(btnMsg2)
                    .addComponent(btnMsg3)
                    .addComponent(btnMsg4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int a = 1;
    private void btnGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGombActionPerformed
        lblSzam.setText(a+"");
        a+=5;
    }//GEN-LAST:event_btnGombActionPerformed

    private void sldCsuszkaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldCsuszkaStateChanged
        lblSzam.setText(sldCsuszka.getValue()+"");
        if (sldCsuszka.getValue() < 60){
            JOptionPane.showMessageDialog(null,"60 alá nem mehet.");
            sldCsuszka.setValue(75);
        }
    }//GEN-LAST:event_sldCsuszkaStateChanged

    private void btnMsg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsg1ActionPerformed
        JOptionPane.showMessageDialog(null, "Alap üzenet.");
    }//GEN-LAST:event_btnMsg1ActionPerformed

    private void btnMsg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsg2ActionPerformed
        JOptionPane.showMessageDialog(null,"Figyelmeztetve vagy!","Figyelmeztető",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnMsg2ActionPerformed

    private void btnMsg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsg3ActionPerformed
        JOptionPane.showMessageDialog(null,"Hiba","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnMsg3ActionPerformed

    private void btnMsg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsg4ActionPerformed
        JOptionPane.showMessageDialog(null,"Üres üzenet.","Üres ablak",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnMsg4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ismetles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ismetles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ismetles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ismetles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ismetles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGomb;
    private javax.swing.JButton btnMsg1;
    private javax.swing.JButton btnMsg2;
    private javax.swing.JButton btnMsg3;
    private javax.swing.JButton btnMsg4;
    private javax.swing.JButton btnSzamol;
    private javax.swing.JLabel lblEredmeny;
    private javax.swing.JLabel lblSzam;
    private javax.swing.JSlider sldCsuszka;
    private javax.swing.JTextField tfSzam;
    // End of variables declaration//GEN-END:variables
}
