// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopData.Models;

public partial class Token
{
    public string GUID { get; set; }

    public DateTime Created { get; set; }

    public TimeOnly Expiration { get; set; }

    public int UserID { get; set; }

    public virtual User User { get; set; }
}