/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Listadoboz;

import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author wuncs.david
 */
public class frmListak extends javax.swing.JFrame {

    DefaultListModel<String> nevek = new DefaultListModel<>();
    static DefaultListModel<String> szurt = new DefaultListModel<>();
    public frmListak() {
        initComponents();
        
        lbNevek.setModel(nevek);
        
        for (int i = 0; i < 100; i++) {
            nevek.addElement("Név"+i);
        }
        lbSzurt.setModel(szurt);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lbNevek = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbSzurt = new javax.swing.JList();
        btnBalrol = new javax.swing.JButton();
        btnJobbrol = new javax.swing.JButton();
        btnMegnyit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lbNevek);

        lbSzurt.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lbSzurt);

        btnBalrol.setText(">>");
        btnBalrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalrolActionPerformed(evt);
            }
        });

        btnJobbrol.setText("<<");
        btnJobbrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobbrolActionPerformed(evt);
            }
        });

        btnMegnyit.setText("Fájlba");
        btnMegnyit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegnyitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnJobbrol, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(btnBalrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMegnyit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnBalrol)
                        .addGap(50, 50, 50)
                        .addComponent(btnJobbrol)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMegnyit)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int [] indexek;
    private void btnBalrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalrolActionPerformed
//       szurt.addElement(lbNevek.getSelectedValue()+"");
       //szurt.addElement(nevek.get(lbNevek.getSelectedIndex()));
       //nevek.remove(lbNevek.getSelectedIndex());
//       nevek.removeElement(lbNevek.getSelectedValue());
       indexek = lbNevek.getSelectedIndices();
        System.out.println(Arrays.toString(indexek));
       //lbNevek.getSelectedValuesList()
//        for(int index : lbNevek.getSelectedIndices()){
//            szurt.addElement(nevek.get(index));
//            
//        }
//        for (int i = indexek.length-1; i >= 0; i--) {
//            nevek.remove(indexek[i]);
//        }
        
        if (lbNevek.getSelectedIndex() != -1){
            for(Object n : lbNevek.getSelectedValuesList()){
                szurt.addElement(n+"");
                nevek.removeElement(n);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Nincs semmi kijelölve");
        }
        
    }//GEN-LAST:event_btnBalrolActionPerformed

    private void btnJobbrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobbrolActionPerformed
        if (lbSzurt.getSelectedIndex() != -1){
            for (Object n : lbSzurt.getSelectedValuesList()){
                nevek.addElement(n+"");
                szurt.removeElement(n);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Nincs semmi kijelölve.");
        }
    }//GEN-LAST:event_btnJobbrolActionPerformed

    private void btnMegnyitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegnyitActionPerformed
        
        if (szurt.size() > 0){
            frmKiir fk = new frmKiir();
            fk.setVisible(true);
        }
        else JOptionPane.showMessageDialog(null,"Üres a lista.");
    }//GEN-LAST:event_btnMegnyitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalrol;
    private javax.swing.JButton btnJobbrol;
    private javax.swing.JButton btnMegnyit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lbNevek;
    private javax.swing.JList lbSzurt;
    // End of variables declaration//GEN-END:variables
}
