// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.Models;

public partial class Cart
{
    public int CartID { get; set; }

    public int UserID { get; set; }

    public int ProductID { get; set; }

    public decimal Quantity { get; set; }

    public DateTime Created { get; set; }

    public DateTime Modified { get; set; }

    public virtual User User { get; set; }
}