/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1013_2223_14b_kolcsonzes;

import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wuncs.david
 */
public class frmAlap extends javax.swing.JFrame {

    /**
     * Creates new form frmAlap
     */
    public frmAlap() {
        initComponents();
        btnBefogad.setVisible(false);
        lblKep.setText("");
        lbAdatok.setModel(frmBej.szabad_tulajok);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbAdatok = new javax.swing.JList();
        rbTulajok = new javax.swing.JRadioButton();
        rbCicak = new javax.swing.JRadioButton();
        lblKep = new javax.swing.JLabel();
        lblTulaj = new javax.swing.JLabel();
        lblCica = new javax.swing.JLabel();
        btnBefogad = new javax.swing.JButton();
        rbSzabad = new javax.swing.JRadioButton();
        rbFoglalt = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbAdatok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAdatokMouseClicked(evt);
            }
        });
        lbAdatok.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbAdatokValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lbAdatok);

        buttonGroup1.add(rbTulajok);
        rbTulajok.setSelected(true);
        rbTulajok.setText("Tulajok");
        rbTulajok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTulajokActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCicak);
        rbCicak.setText("Cicák");
        rbCicak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCicakActionPerformed(evt);
            }
        });

        lblKep.setText("jLabel1");

        lblTulaj.setText("Örökbefogadó neve: ");

        lblCica.setText("Cica neve: ");

        btnBefogad.setText("Örökbefogadás");
        btnBefogad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBefogadActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbSzabad);
        rbSzabad.setSelected(true);
        rbSzabad.setText("Szabad");
        rbSzabad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSzabadActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbFoglalt);
        rbFoglalt.setText("Foglalt");
        rbFoglalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFoglaltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbSzabad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbFoglalt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbTulajok)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTulaj)
                            .addComponent(lblCica)
                            .addComponent(rbCicak))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnBefogad)))
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTulaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCica)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTulajok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCicak))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblKep, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBefogad)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSzabad)
                    .addComponent(rbFoglalt))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbTulajokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTulajokActionPerformed
        if (rbSzabad.isSelected())
            lbAdatok.setModel(frmBej.szabad_tulajok);
        else if (rbFoglalt.isSelected())
            lbAdatok.setModel(frmBej.foglalt_tulajok);
        
    }//GEN-LAST:event_rbTulajokActionPerformed

    private void rbCicakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCicakActionPerformed
        if (rbSzabad.isSelected())
            lbAdatok.setModel(frmBej.szabad_cicak);
        else if (rbFoglalt.isSelected())
            lbAdatok.setModel(frmBej.foglalt_cicak);
        
    }//GEN-LAST:event_rbCicakActionPerformed

    private void lbAdatokValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbAdatokValueChanged
        if (rbCicak.isSelected() &&
            lbAdatok.getSelectedIndex() != -1){
            if (rbSzabad.isSelected()){
            lblKep.setIcon(frmBej.szabad_cicak.get(
            lbAdatok.getSelectedIndex()).getKep());
            }
            else if (rbFoglalt.isSelected()){
            lblKep.setIcon(frmBej.foglalt_cicak.get(
            lbAdatok.getSelectedIndex()).getKep()); 
            }
            
        }
    }//GEN-LAST:event_lbAdatokValueChanged
    
    static Tulaj ta;
    static Cica ca;
    static boolean tv = false;
    static boolean cv = false;
    static int t_index;
    static int c_index;
    static boolean f_tv = false;
    static boolean f_cv = false;
    private void lbAdatokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAdatokMouseClicked
        if (evt.getClickCount() == 2){
            if (rbSzabad.isSelected()){
            if (rbTulajok.isSelected()){
                t_index = lbAdatok.getSelectedIndex();
                lblTulaj.setText("Örökbefogadó neve: "+
                frmBej.szabad_tulajok.get(
                lbAdatok.getSelectedIndex()).getNev());
                ta = frmBej.szabad_tulajok.get(
                lbAdatok.getSelectedIndex());
                tv = true;
            }
            else{
                c_index = lbAdatok.getSelectedIndex();
                lblCica.setText("Cica neve: "+
                frmBej.szabad_cicak.get(
                lbAdatok.getSelectedIndex()).getNev());
                ca = frmBej.szabad_cicak.get(
                lbAdatok.getSelectedIndex());
                cv = true;
            }
            if (tv && cv){
                btnBefogad.setText("Befogad");
                btnBefogad.setVisible(true);
            }
            }
            else if (rbFoglalt.isSelected()){
                if (rbTulajok.isSelected()){
                t_index = lbAdatok.getSelectedIndex();
                lblTulaj.setText("Örökbefogadó neve: "+
                frmBej.foglalt_tulajok.get(
                lbAdatok.getSelectedIndex()).getNev());
                ta = frmBej.foglalt_tulajok.get(
                lbAdatok.getSelectedIndex());
                f_tv = true;
            }
            else{
                c_index = lbAdatok.getSelectedIndex();
                lblCica.setText("Cica neve: "+
                frmBej.foglalt_cicak.get(
                lbAdatok.getSelectedIndex()).getNev());
                ca = frmBej.foglalt_cicak.get(
                lbAdatok.getSelectedIndex());
                f_cv = true;
            }
            if (f_tv && f_cv){
                btnBefogad.setText("Felold");
                btnBefogad.setVisible(true);
            }
                
            }
        }
    }//GEN-LAST:event_lbAdatokMouseClicked

    private void btnBefogadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBefogadActionPerformed
        if (btnBefogad.getText().equals("Befogad")){
        Tars t = new Tars(ta, ca);
        kiir(t);
        frmBej.szabad_cicak.get(c_index).setFoglalt("Igen");
        frissit(frmBej.path_c);
        frmBej.szabad_cicak.removeElement(ca);
        frmBej.foglalt_cicak.addElement(ca);
        
        frmBej.szabad_tulajok.get(t_index).setTul("Igen");
        frissit_tulaj(frmBej.path_t);
        frmBej.szabad_tulajok.removeElement(ta);
        frmBej.foglalt_tulajok.addElement(ta);
        
        btnBefogad.setVisible(false);
        cv = false;
        tv = false;
        }
        else if (btnBefogad.getText().equals("Felold")){
        Tars t = new Tars(ta, ca);
        
        frmBej.foglalt_cicak.get(c_index).setFoglalt("Nem");
        frissit(frmBej.path_c);
        frmBej.foglalt_cicak.removeElement(ca);
        frmBej.szabad_cicak.addElement(ca);
        
        frmBej.foglalt_tulajok.get(t_index).setTul("Nem");
        frissit_tulaj(frmBej.path_t);
        frmBej.foglalt_tulajok.removeElement(ta);
        frmBej.szabad_tulajok.addElement(ta);
        
        btnBefogad.setVisible(false);
        f_cv = false;
        f_tv = false; 
        }
    }//GEN-LAST:event_btnBefogadActionPerformed

    private void rbSzabadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSzabadActionPerformed
        f_cv = false;
        f_tv = false;
        btnBefogad.setVisible(false);
        if (rbTulajok.isSelected())
            lbAdatok.setModel(frmBej.szabad_tulajok);
        else if (rbCicak.isSelected())
            lbAdatok.setModel(frmBej.szabad_cicak);
    }//GEN-LAST:event_rbSzabadActionPerformed

    private void rbFoglaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFoglaltActionPerformed
        cv = false;
        tv = false;
        btnBefogad.setVisible(false);
        if (rbTulajok.isSelected())
            lbAdatok.setModel(frmBej.foglalt_tulajok);
        else if (rbCicak.isSelected())
            lbAdatok.setModel(frmBej.foglalt_cicak);
    }//GEN-LAST:event_rbFoglaltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBefogad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lbAdatok;
    private javax.swing.JLabel lblCica;
    private javax.swing.JLabel lblKep;
    private javax.swing.JLabel lblTulaj;
    private javax.swing.JRadioButton rbCicak;
    private javax.swing.JRadioButton rbFoglalt;
    private javax.swing.JRadioButton rbSzabad;
    private javax.swing.JRadioButton rbTulajok;
    // End of variables declaration//GEN-END:variables

    private void kiir(Tars t) {
        try {
            FileWriter fw =
               new FileWriter("Befogadasok.csv",true);
            fw.write(t+"\n");
            fw.close();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }

    private void frissit(String path_c) {
        try {
            FileWriter fw = new FileWriter(path_c);
            fw.write("Nev;Kor(honap);Kep;Foglalt\n");
            for (int i = 0; i < frmBej.szabad_cicak.getSize(); i++) {
                fw.write(frmBej.szabad_cicak.get(i).getNev()+";"+
                        frmBej.szabad_cicak.get(i).getKor()+";"+
               frmBej.szabad_cicak.get(i).getKep().getDescription()+";"+
                        frmBej.szabad_cicak.get(i).getFoglalt()+"\n");
            }
            for (int i = 0; i < frmBej.foglalt_cicak.getSize(); i++) {
                fw.write(frmBej.foglalt_cicak.get(i).getNev()+";"+
                        frmBej.foglalt_cicak.get(i).getKor()+";"+
               frmBej.foglalt_cicak.get(i).getKep().getDescription()+";"+
                        frmBej.foglalt_cicak.get(i).getFoglalt()+"\n");
            }
            fw.close();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }

    private void frissit_tulaj(String path_t) {
        try {
            FileWriter fw = new FileWriter(path_t);
            fw.write("Nev;Kor;Tulajdonos\n");
            for (int i = 0; i < frmBej.szabad_tulajok.getSize(); i++) {
                fw.write(frmBej.szabad_tulajok.get(i).getNev()+";"+
                        frmBej.szabad_tulajok.get(i).getKor()+";"+
               frmBej.szabad_tulajok.get(i).getTul()+"\n");
            }
            for (int i = 0; i < frmBej.foglalt_tulajok.getSize(); i++) {
                fw.write(frmBej.foglalt_tulajok.get(i).getNev()+";"+
                        frmBej.foglalt_tulajok.get(i).getKor()+";"+
               frmBej.foglalt_tulajok.get(i).getTul()+"\n");
            }
            fw.close();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }
}
