/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1109_2324_14b;

import java.io.File;
import java.util.Scanner;
import javax.swing.DefaultListModel;

/**
 *
 * @author wuncs.david
 */
public class frmAcb extends javax.swing.JFrame {

    DefaultListModel<Eredmeny> eredmenyek =
            new DefaultListModel<>();    
    public frmAcb() {
        initComponents();
        lbEredmenyek.setModel(eredmenyek);
        feltolt();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lbEredmenyek = new javax.swing.JList();
        lblCsapatok = new javax.swing.JLabel();
        lblEredmeny = new javax.swing.JLabel();
        lblStadion = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblF3 = new javax.swing.JLabel();
        lblF4 = new javax.swing.JLabel();
        lblF5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taF6 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taF7 = new javax.swing.JTextArea();
        btnMegold = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbEredmenyek.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lbEredmenyek.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbEredmenyekValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lbEredmenyek);

        lblCsapatok.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCsapatok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCsapatok.setText("lblCsapatok");

        lblEredmeny.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblEredmeny.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEredmeny.setText("lblEredmeny");

        lblStadion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblStadion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStadion.setText("lblStadion");

        lblDatum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblDatum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatum.setText("lblDatum");

        lblF3.setText("lblF3");

        lblF4.setText("lblF4");

        lblF5.setText("lblF5");

        taF6.setColumns(20);
        taF6.setRows(5);
        jScrollPane2.setViewportView(taF6);

        taF7.setColumns(20);
        taF7.setRows(5);
        jScrollPane3.setViewportView(taF7);

        btnMegold.setText("Megold");
        btnMegold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegoldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCsapatok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEredmeny, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE)
                            .addComponent(lblStadion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblF3, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblF4, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblF5, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMegold)
                .addGap(553, 553, 553))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCsapatok)
                        .addGap(18, 18, 18)
                        .addComponent(lblEredmeny)
                        .addGap(18, 18, 18)
                        .addComponent(lblStadion)
                        .addGap(18, 18, 18)
                        .addComponent(lblDatum)
                        .addGap(143, 143, 143)
                        .addComponent(lblF3)
                        .addGap(18, 18, 18)
                        .addComponent(lblF4)
                        .addGap(18, 18, 18)
                        .addComponent(lblF5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnMegold)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbEredmenyekValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbEredmenyekValueChanged
        int index = lbEredmenyek.getSelectedIndex();
        lblCsapatok.setText(
        eredmenyek.get(index).h_nev+" - "+
        eredmenyek.get(index).v_nev);
        //-------------------------------------------------------
        lblEredmeny.setText(eredmenyek.get(index).h_pont+" : "+
                            eredmenyek.get(index).v_pont);
        
        lblStadion.setText(eredmenyek.get(index).hely);
        
        lblDatum.setText(eredmenyek.get(index).datum);
    }//GEN-LAST:event_lbEredmenyekValueChanged

    private void btnMegoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegoldActionPerformed
        _f3();
        lblF4.setText(_f4());
        lblF5.setText(_f5());
    }//GEN-LAST:event_btnMegoldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAcb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAcb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAcb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAcb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAcb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegold;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lbEredmenyek;
    private javax.swing.JLabel lblCsapatok;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblEredmeny;
    private javax.swing.JLabel lblF3;
    private javax.swing.JLabel lblF4;
    private javax.swing.JLabel lblF5;
    private javax.swing.JLabel lblStadion;
    private javax.swing.JTextArea taF6;
    private javax.swing.JTextArea taF7;
    // End of variables declaration//GEN-END:variables

    private void feltolt() {
        File f = new File("eredmenyek.csv");
        try {
            Scanner be = new Scanner(f,"ISO-8859-2");
            be.nextLine();
            String sor;
            String [] adatok;
            while(be.hasNextLine()){
                sor = be.nextLine();
                adatok = sor.split(";");
                eredmenyek.addElement(new Eredmeny(
                adatok[0], adatok[1],
                Integer.parseInt(adatok[2]),Integer.parseInt(adatok[3]),
                 adatok[4], adatok[5]));
            }
        } catch (Exception e) {
            System.out.println("Hiba: "+e);
        }
    }

    private void _f3() {
        int h = 0;
        int v = 0;
        
        for (int i = 0; i < eredmenyek.size(); i++) {
            if (eredmenyek.get(i).
              h_nev.contains("Real Madrid"))
                h++;
            if (eredmenyek.get(i).
              v_nev.contains("Real Madrid"))
                v++;
        }
        
        lblF3.setText("Hazai: "+h+", Vendég: "+v);
        
    }

    private String _f4() {
        for (int i = 0; i < eredmenyek.size(); i++) {
            if (eredmenyek.get(i).h_pont ==
                eredmenyek.get(i).v_pont)
                return "Volt döntetlen.";
        }
        
        return "Nem volt döntetlen.";
    }

    private String _f5() {
        
        for (int i = 0; i < eredmenyek.size(); i++) {
            if (eredmenyek.get(i).
                h_nev.contains("Barcelona"))
                return eredmenyek.get(i).h_nev;
        }
        
        return "Nincs ilyen csapat.";
    }
}
