/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gy0212_2526_14;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author wuncs.david
 */
public class frmDesign extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmDesign.class.getName());

    /**
     * Creates new form frmDesign
     */
    Random rnd = new Random();
    public frmDesign() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHatter = new javax.swing.JButton();
        btnGomb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHatter.setBackground(new java.awt.Color(0, 255, 255));
        btnHatter.setForeground(new java.awt.Color(255, 0, 51));
        btnHatter.setText("Háttér");
        btnHatter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHatterActionPerformed(evt);
            }
        });

        btnGomb.setMaximumSize(new java.awt.Dimension(50, 50));
        btnGomb.setMinimumSize(new java.awt.Dimension(50, 50));
        btnGomb.setPreferredSize(new java.awt.Dimension(50, 50));
        btnGomb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGombMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGombMouseExited(evt);
            }
        });
        btnGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnHatter, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(btnHatter, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHatterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHatterActionPerformed
        Color rgb = new Color(
                rnd.nextInt(0,256),
                rnd.nextInt(0, 256),
                rnd.nextInt(0, 256));
        this.getContentPane().setBackground(rgb);
    }//GEN-LAST:event_btnHatterActionPerformed

    private void btnGombMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGombMouseEntered
        Color rgb = new Color(
                rnd.nextInt(0,256),
                rnd.nextInt(0, 256),
                rnd.nextInt(0, 256));
        btnHatter.setBackground(rgb);
    }//GEN-LAST:event_btnGombMouseEntered

    private void btnGombMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGombMouseExited
       
        Color rgb = new Color(
                rnd.nextInt(0,256),
                rnd.nextInt(0, 256),
                rnd.nextInt(0, 256));
        btnHatter.setForeground(rgb);
            
            
        
    }//GEN-LAST:event_btnGombMouseExited

    private void btnGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGombActionPerformed
        System.out.println(this.getContentPane().getBackground());
        System.out.println(btnHatter.getBackground());
        System.out.println(btnHatter.getForeground());
    }//GEN-LAST:event_btnGombActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmDesign().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGomb;
    private javax.swing.JButton btnHatter;
    // End of variables declaration//GEN-END:variables
}
