// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopData.Models;

public partial class ProductPicture
{
    public int ProductPictureID { get; set; }

    public int ProductID { get; set; }

    public string Title { get; set; }

    public byte[] Trumbnail { get; set; }

    public byte[] Picture { get; set; }

    public virtual Product Product { get; set; }
}