/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1107_2425_14b_masodfok;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author wuncs.david
 */
public class frmMasodfok extends javax.swing.JFrame {

    /**
     * Creates new form frmMasodfok
     */
    public frmMasodfok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfA = new javax.swing.JTextField();
        tfB = new javax.swing.JTextField();
        tfC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMegold = new javax.swing.JButton();
        lblMegold = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfA.setToolTipText("'A' értéke");
        tfA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfAKeyPressed(evt);
            }
        });

        tfB.setToolTipText("'B' értéke");
        tfB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBKeyPressed(evt);
            }
        });

        tfC.setToolTipText("'C' értéke");
        tfC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCKeyPressed(evt);
            }
        });

        jLabel1.setText("A:");

        jLabel2.setText("B:");

        jLabel3.setText("C:");

        btnMegold.setText("Megoldás");
        btnMegold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegoldActionPerformed(evt);
            }
        });

        lblMegold.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMegold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMegold.setText("Eredmény");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMegold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfA, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfB, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(btnMegold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnMegold, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lblMegold)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMegoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegoldActionPerformed
        masodfok();
    }//GEN-LAST:event_btnMegoldActionPerformed

    private void tfAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            tfB.requestFocus();
        
    }//GEN-LAST:event_tfAKeyPressed

    private void tfBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            tfC.requestFocus();
    }//GEN-LAST:event_tfBKeyPressed

    private void tfCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            masodfok();
    }//GEN-LAST:event_tfCKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMasodfok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMasodfok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMasodfok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMasodfok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMasodfok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegold;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMegold;
    private javax.swing.JTextField tfA;
    private javax.swing.JTextField tfB;
    private javax.swing.JTextField tfC;
    // End of variables declaration//GEN-END:variables

    private void masodfok() {
        try{
            double a = Double.parseDouble(tfA.getText());
            if (a!=0){
                double b = Double.parseDouble(tfB.getText());
                double c = Double.parseDouble(tfC.getText());
                double diszkr = b*b-4*a*c;
                if (diszkr > 0){
                    double x1 = (-b+Math.sqrt(diszkr))/(2*a);
                    double x2 = (-b-Math.sqrt(diszkr))/(2*a);
                    System.out.printf("x1: %.2f, x2: %.2f ",x1,x2);
                    lblMegold.setText(String.format("x1: %.2f, x2: %.2f ",x1,x2));
                }
                else if (diszkr == 0){
                    double x = -b/(2*a);
                    System.out.println("x: "+x);
                    lblMegold.setText(String.format("x: %.2f",x));
                }
                else{
                    System.out.println("Nincs valós megoldás!");
                    lblMegold.setText("Nincs valós megoldás");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"'A' értéke nem lehet 0!");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,"A mezõkbe CSAK valós SZÁMOK kerülhetnek!");
        }
    }
}
