/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1205_2425_14b_acbgrafikus;

import java.io.File;
import java.util.Scanner;
import javax.swing.DefaultListModel;

/**
 *
 * @author wuncs.david
 */
public class frmKosar extends javax.swing.JFrame {

    static DefaultListModel<Eredmeny> eredmenyek =
            new DefaultListModel<>();
    public frmKosar() {
        initComponents();
        lbEred.setModel(eredmenyek);
        feltolt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lbEred = new javax.swing.JList();
        btnF3 = new javax.swing.JButton();
        btnF4 = new javax.swing.JButton();
        btnF5 = new javax.swing.JButton();
        btnF6 = new javax.swing.JButton();
        btnF7 = new javax.swing.JButton();
        lblF3 = new javax.swing.JLabel();
        lblF4 = new javax.swing.JLabel();
        lblF5 = new javax.swing.JLabel();
        lblF6 = new javax.swing.JLabel();
        lblF7 = new javax.swing.JLabel();
        btnMegnyit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbEred.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lbEred);

        btnF3.setText("3. Feladat");
        btnF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF3ActionPerformed(evt);
            }
        });

        btnF4.setText("4. Feladat");

        btnF5.setText("5. Feladat");

        btnF6.setText("6. Feladat");

        btnF7.setText("7. Feladat");

        lblF3.setText("jLabel1");

        lblF4.setText("jLabel1");

        lblF5.setText("jLabel1");

        lblF6.setText("jLabel1");

        lblF7.setText("jLabel1");

        btnMegnyit.setText("Megnyit");
        btnMegnyit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegnyitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnF6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblF6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnF7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblF7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnF3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblF3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnF4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblF4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnF5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblF5))))
                    .addComponent(btnMegnyit))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnF3)
                            .addComponent(lblF3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnF4)
                            .addComponent(lblF4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnF5)
                            .addComponent(lblF5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnF6)
                            .addComponent(lblF6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnF7)
                            .addComponent(lblF7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnMegnyit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int h;
    int v;
    private void btnF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF3ActionPerformed
        h = 0;
        v = 0;
        for (int i = 0; i < eredmenyek.size(); i++) {
            if (eredmenyek.get(i)
                    .getH_nev()
                    .equals("Real Madrid"))
                h++;
            if (eredmenyek.get(i)
                    .getV_nev()
                    .equals("Real Madrid"))
                v++;
        }
        lblF3.setText(
        String.format(
        "Hazai: %d Vendég: %d", h,v));
    }//GEN-LAST:event_btnF3ActionPerformed

    private void btnMegnyitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegnyitActionPerformed
        frmMasodik fm = new frmMasodik();
        fm.setVisible(true);
    }//GEN-LAST:event_btnMegnyitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKosar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKosar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKosar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKosar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKosar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnF3;
    private javax.swing.JButton btnF4;
    private javax.swing.JButton btnF5;
    private javax.swing.JButton btnF6;
    private javax.swing.JButton btnF7;
    private javax.swing.JButton btnMegnyit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lbEred;
    private javax.swing.JLabel lblF3;
    private javax.swing.JLabel lblF4;
    private javax.swing.JLabel lblF5;
    private javax.swing.JLabel lblF6;
    private javax.swing.JLabel lblF7;
    // End of variables declaration//GEN-END:variables

    private void feltolt() {
        File f = new File("eredmenyek.csv");
        try {
            Scanner be = new Scanner(f,"ISO-8859-2");
            String sor;
            String []adatok;
            be.nextLine();
            while(be.hasNextLine()){
                sor = be.nextLine();
                adatok = sor.split(";");
                eredmenyek.addElement(
                new Eredmeny(adatok[0], adatok[1],
                        Integer.parseInt(adatok[2]),
                        Integer.parseInt(adatok[3]),
                        adatok[4],adatok[5]));
            }
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
