/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1114_2425_14a;

import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author wuncs.david
 */
public class frmListak extends javax.swing.JFrame {

    DefaultListModel<String> bal = new DefaultListModel<>();
    DefaultListModel<String> jobb = new DefaultListModel<>();
    public frmListak() {
        initComponents();
        lbBal.setModel(bal);
        lbJobb.setModel(jobb);
        
        for (int i = 1; i < 101; i++) {
            bal.addElement("Elem"+i);
        }
        /*Feladat: A gomb LENYOMÁSÁRA kerüljön át a baloldali lista
        kijelölt eleme a jobboldali listába. Balról törlődjön!*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lbBal = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbJobb = new javax.swing.JList();
        btnBalJobb = new javax.swing.JButton();
        btnJobbBal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbBal.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lbBal);

        lbJobb.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lbJobb);

        btnBalJobb.setText("-->");
        btnBalJobb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalJobbActionPerformed(evt);
            }
        });

        btnJobbBal.setText("<--");
        btnJobbBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobbBalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBalJobb)
                    .addComponent(btnJobbBal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnBalJobb)
                        .addGap(37, 37, 37)
                        .addComponent(btnJobbBal)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBalJobbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalJobbActionPerformed
        
        if (lbBal.getSelectedIndex() != -1){
            
            for (Object elem : lbBal.getSelectedValues()){
                jobb.addElement(elem+"");
                bal.removeElement(elem);
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this,"Nincs semmi kijelölve...");
        }
        
//        jobb.addElement(bal.get(lbBal.getSelectedIndex()));
//        bal.remove(lbBal.getSelectedIndex());
        
    }//GEN-LAST:event_btnBalJobbActionPerformed
    /*Feladat: Módosítsa úgy a gombok eventjeit, hogy ha nincs semmi
    kijelölve akkor a felhasználó kapjon egy üzenetet!
    Feladat: Módosítsa úgy a programot, hogy többszörös kijelölés esetén
    minden elemet tegyen át a másik listadobozba, illetve törölje őket
    az eredeti listából.*/
    private void btnJobbBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobbBalActionPerformed
        
        if (lbJobb.getSelectedIndex() != -1){
                for (Object elem : lbJobb.getSelectedValues()){
                        bal.addElement(elem+"");
                        jobb.removeElement(elem);
                    }
        }
        else{
            JOptionPane.showMessageDialog(this,"Nincs semmi kijelölve...");
        }
    }//GEN-LAST:event_btnJobbBalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalJobb;
    private javax.swing.JButton btnJobbBal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lbBal;
    private javax.swing.JList lbJobb;
    // End of variables declaration//GEN-END:variables
}
