// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.Models;

public partial class ProductImage
{
    public int ProductImageID { get; set; }

    public string Description { get; set; }

    public int ProductID { get; set; }

    public byte[] Image { get; set; }

    public bool Enable { get; set; }

    public virtual Product Product { get; set; }
}