/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApplication231;

import java.io.File;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author wuncs.david
 */
public class frmORszagok extends javax.swing.JFrame {

    DefaultListModel<Orszag> orszagok =
            new DefaultListModel<>();
    public frmORszagok() {
        initComponents();
        lbOrszagok.setModel(orszagok);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbOrszagok = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbTobb = new javax.swing.JRadioButton();
        rbKevesebb = new javax.swing.JRadioButton();
        btnSzamol = new javax.swing.JButton();
        tfSzamol = new javax.swing.JTextField();
        btnKiir = new javax.swing.JButton();
        btnAvg = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        cbNep = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mEu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbOrszagok.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lbOrszagok);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Országok népessége");

        jLabel2.setText("Mit számoljak?");

        jLabel3.setText("legkisebb/legnagyobb népesség:");

        buttonGroup1.add(rbTobb);
        rbTobb.setText("10 milliónál több");

        buttonGroup1.add(rbKevesebb);
        rbKevesebb.setText("legfeljebb 10 millió");

        btnSzamol.setText("megszámol");
        btnSzamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSzamolActionPerformed(evt);
            }
        });

        tfSzamol.setEditable(false);

        btnKiir.setText("Kiír");

        btnAvg.setText("Átlag");

        btnExit.setText("Kilépés");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        cbNep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Legnagyobb", "Legkisebb" }));

        mFile.setText("Fájl");
        mFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mFileMouseClicked(evt);
            }
        });
        jMenuBar1.add(mFile);

        mEu.setText("Európai");
        jMenuBar1.add(mEu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbKevesebb)
                            .addComponent(rbTobb)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSzamol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfSzamol, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbNep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKiir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTobb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbKevesebb)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSzamol)
                            .addComponent(tfSzamol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKiir)
                            .addComponent(cbNep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAvg)
                            .addComponent(btnExit))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    int re;
    private void mFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mFileMouseClicked
        JFileChooser fc = new JFileChooser();
         re = fc.showOpenDialog(this);
         
         if (re == 0){
             feltolt(fc.getSelectedFile());
             
         }
    }//GEN-LAST:event_mFileMouseClicked

    private void btnSzamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSzamolActionPerformed
        if (rbTobb.isSelected()){
            tfSzamol.setText(megszamol(true)+"");
        }
        else if (rbKevesebb.isSelected()){
            tfSzamol.setText(megszamol(false)+"");
        }
    }//GEN-LAST:event_btnSzamolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmORszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmORszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmORszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmORszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmORszagok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvg;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnKiir;
    private javax.swing.JButton btnSzamol;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbNep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lbOrszagok;
    private javax.swing.JMenu mEu;
    private javax.swing.JMenu mFile;
    private javax.swing.JRadioButton rbKevesebb;
    private javax.swing.JRadioButton rbTobb;
    private javax.swing.JTextField tfSzamol;
    // End of variables declaration//GEN-END:variables

    private void feltolt(File f) {
        try {
            Scanner be = new Scanner(f,"ISO-8859-2");
//            String sor;
//            String adatok [];
            
            while(be.hasNextLine()){
                orszagok.addElement(new Orszag(
                be.nextLine(),
                Integer.parseInt(be.nextLine()),
                be.nextLine()));
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private int megszamol(boolean tobb) {
        int k = 0;
        int t = 0;
        
        for (int i = 0; i < orszagok.size(); i++) {
            if (orszagok.get(i).getFo() > 10000)
                t++;
            else
                k++;
        }
        
        if (tobb) return t;
        else return k;
        
    }
}
