/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1114_2425_14b;

import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author wuncs.david
 */
public class frmListak extends javax.swing.JFrame {

    DefaultListModel<String> adatok =
            new DefaultListModel<>();
    DefaultListModel<String> jobb =
            new DefaultListModel<>();
    public frmListak() {
        initComponents();
        lbJobb.setModel(jobb);
        //lblTobbsor.setText(mlc("Jó lenne\nha több\nsor lenne."));
        lblTobbsor.setText("Kiválasztott index: "+lbAdatok.getSelectedIndex());
//        lbAdatok.setSelectedIndex(2);
        //lbAdatok.setSelectedIndex(-1);
        lbAdatok.setModel(adatok);
        feltolt();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTobbsor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbAdatok = new javax.swing.JList();
        btnDel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbJobb = new javax.swing.JList();
        btnBalJobb = new javax.swing.JButton();
        btnJobbBal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTobbsor.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        lblTobbsor.setText("jLabel1");

        lbAdatok.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lbAdatok.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbAdatokValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lbAdatok);

        btnDel.setText("Törlés");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        lbJobb.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lbJobb.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbJobbValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lbJobb);

        btnBalJobb.setText("-->");
        btnBalJobb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalJobbActionPerformed(evt);
            }
        });

        btnJobbBal.setText("<--");
        btnJobbBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobbBalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnDel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTobbsor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBalJobb, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnJobbBal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTobbsor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBalJobb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnJobbBal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDel)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbAdatokValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbAdatokValueChanged
//        lblTobbsor.setText("Kiválasztott index: "+lbAdatok.getSelectedIndex());
//        lblTobbsor.setText("Kiválasztott elem: "+lbAdatok.getSelectedValue());
        lblTobbsor.setText(mlc("Kiválasztott index: "+
                lbAdatok.getSelectedIndex()+
                "\nKiválasztott elem: "+
                lbAdatok.getSelectedValue()));
    }//GEN-LAST:event_lbAdatokValueChanged

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        //adatok.remove(lbAdatok.getSelectedIndex());
        if (lbAdatok.getSelectedIndex() != -1)
            adatok.removeElement(lbAdatok.getSelectedValue());
        else
            JOptionPane.showMessageDialog(this,"Nincs semmi kijelölve");
    }//GEN-LAST:event_btnDelActionPerformed

    private void lbJobbValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbJobbValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lbJobbValueChanged

    private void btnBalJobbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalJobbActionPerformed
        if (lbAdatok.getSelectedIndex() != -1){
//            jobb.addElement(lbAdatok.getSelectedValue()+"");
//            //jobb.addElement(adatok.get(lbAdatok.getSelectedIndex()));
//            adatok.removeElement(lbAdatok.getSelectedValue());
//            //adatok.remove(lbAdatok.getSelectedIndex());
            System.out.println(Arrays.toString(lbAdatok.getSelectedIndices()));
            System.out.println(Arrays.toString(lbAdatok.getSelectedValues()));
//            for (int i = 0; i < lbAdatok.getSelectedIndices().length; i++) {
//                jobb.addElement(adatok.get(lbAdatok.getSelectedIndices()[i]));
//                adatok.remove(lbAdatok.getSelectedIndices()[i]);
            //Ez még hibás
//            }
            
            for (Object elem : lbAdatok.getSelectedValues()){
                jobb.addElement(elem+"");
                adatok.removeElement(elem);
            }
            
        }
        else
            JOptionPane.showMessageDialog(this,"Nincs semmi kijelölve!");
    }//GEN-LAST:event_btnBalJobbActionPerformed

    private void btnJobbBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobbBalActionPerformed
        if (lbJobb.getSelectedIndex() != -1){
//            adatok.addElement(lbJobb.getSelectedValue()+"");
//            jobb.removeElement(lbJobb.getSelectedValue());
            for (Object elem : lbJobb.getSelectedValues()){
                adatok.addElement(elem+"");
                jobb.removeElement(elem);
            }
            
            
        }
        else
            JOptionPane.showMessageDialog(this,"Nincs semmi kijelölve!");
    }//GEN-LAST:event_btnJobbBalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalJobb;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnJobbBal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lbAdatok;
    private javax.swing.JList lbJobb;
    private javax.swing.JLabel lblTobbsor;
    // End of variables declaration//GEN-END:variables

    private String mlc(String adat) {
        return "<html>"+adat.replace("\n", "<br>");
    }

    private void feltolt() {
        for (int i = 1; i < 101; i++) {
            adatok.addElement("Elem"+i);
        }
       
    }
}
