/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graf_futok;

import java.io.File;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author wuncs.david
 */
public class frmFutok extends javax.swing.JFrame {

    /**
     * Creates new form frmFutok
     */
    static ArrayList<Futo> futok = new ArrayList<>();
    static DefaultListModel<String> nevek =
            new DefaultListModel<>();
    public frmFutok() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lbNevek = new javax.swing.JList();
        tfRajtszam = new javax.swing.JTextField();
        tfOrszag = new javax.swing.JTextField();
        tfIdo = new javax.swing.JTextField();
        tfKor = new javax.swing.JTextField();
        btnAdatbe = new javax.swing.JButton();
        btnBezar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miBeolvas = new javax.swing.JMenuItem();
        mEredmenyek = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maraton");

        lbNevek.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lbNevek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNevekMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lbNevek);

        tfRajtszam.setEditable(false);

        tfOrszag.setEditable(false);

        tfIdo.setEditable(false);

        tfKor.setEditable(false);

        btnAdatbe.setText("Adat be");
        btnAdatbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdatbeActionPerformed(evt);
            }
        });

        btnBezar.setText("Bezár");
        btnBezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBezarActionPerformed(evt);
            }
        });

        jLabel1.setText("RÉSZTVEVŐK");

        jLabel2.setText("Rajtszám:");

        jLabel3.setText("Ország:");

        jLabel4.setText("Idő:");

        jLabel5.setText("Kor:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("MARATONI FUTÁS");

        mFile.setText("File");

        miBeolvas.setText("Beolvas");
        miBeolvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBeolvasActionPerformed(evt);
            }
        });
        mFile.add(miBeolvas);

        jMenuBar1.add(mFile);

        mEredmenyek.setText("Eredmények");
        mEredmenyek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mEredmenyekMouseClicked(evt);
            }
        });
        jMenuBar1.add(mEredmenyek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(btnAdatbe, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfOrszag, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfIdo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfKor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBezar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tfRajtszam, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfRajtszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfOrszag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdatbe)
                    .addComponent(btnBezar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static JFileChooser fc = new JFileChooser();
    private void miBeolvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBeolvasActionPerformed
        if (futok.isEmpty()){
            try {
                int e = fc.showOpenDialog(this);
                if (e == JFileChooser.APPROVE_OPTION){
                    beolvas();
                }
        } catch (FileNotFoundException | ParseException ex) {
            
        }
        }else
            JOptionPane.showMessageDialog(null,"Már beolvastad!");
       
    }//GEN-LAST:event_miBeolvasActionPerformed

    private void btnBezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBezarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnBezarActionPerformed

    private void btnAdatbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdatbeActionPerformed
        lbNevek.setModel(nevek);
    }//GEN-LAST:event_btnAdatbeActionPerformed

    private void lbNevekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNevekMouseClicked
        tfRajtszam.setText(futok.get(lbNevek.getSelectedIndex()).getRajtszam());
        tfOrszag.setText(futok.get(lbNevek.getSelectedIndex()).getOrszag());
        tfKor.setText(Integer.toString(futok.get(lbNevek.getSelectedIndex()).getKor()));
        SimpleDateFormat sdf = new SimpleDateFormat("mm:ss.SS");
        tfIdo.setText(sdf.format(futok.get(lbNevek.getSelectedIndex()).getIdo()));
    }//GEN-LAST:event_lbNevekMouseClicked

    private void mEredmenyekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mEredmenyekMouseClicked
        Collections.sort(futok);
        frmEredmenyek frm = new frmEredmenyek();
        frm.setVisible(true);
    }//GEN-LAST:event_mEredmenyekMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFutok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFutok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFutok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFutok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFutok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdatbe;
    private javax.swing.JButton btnBezar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lbNevek;
    private javax.swing.JMenu mEredmenyek;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuItem miBeolvas;
    private javax.swing.JTextField tfIdo;
    private javax.swing.JTextField tfKor;
    private javax.swing.JTextField tfOrszag;
    private javax.swing.JTextField tfRajtszam;
    // End of variables declaration//GEN-END:variables

    private void beolvas() throws FileNotFoundException, ParseException {
        File f = fc.getSelectedFile();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy.MM.dd");
        SimpleDateFormat sdf2 = new SimpleDateFormat("mm:ss.SS");
        Scanner be = new Scanner(f,"iso-8859-2");
        String sor;
        String [] adatok;
        while(be.hasNextLine()){
            sor = be.nextLine();
            adatok = sor.split(";");
            futok.add(new Futo(adatok[0], adatok[1],
                    sdf1.parse(adatok[2]), adatok[3], sdf2.parse(adatok[4])));
            nevek.addElement(adatok[1]);
        }
    }
}
