// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopData.Models;

public partial class Cart
{
    public string TokenGUID { get; set; }

    public int ProductID { get; set; }

    public decimal Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public virtual Product Product { get; set; }

    public virtual Token Token { get; set; }
}