// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopData.Models;

public partial class User
{
    public int UserID { get; set; }

    public int EmployeeID { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Token> Tokens { get; set; } = new List<Token>();
}