
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Wuncs.David
 */
public class Mind1 extends javax.swing.JFrame {

    /**
     * Creates new form Mind1
     */
    public Mind1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBeolvas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbJo = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbRossz = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(330, 400));
        getContentPane().setLayout(null);

        btnBeolvas.setText("Beolvas");
        btnBeolvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeolvasActionPerformed(evt);
            }
        });
        getContentPane().add(btnBeolvas);
        btnBeolvas.setBounds(12, 13, 75, 25);

        jScrollPane1.setViewportView(lbJo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 75, 291, 68);

        jScrollPane2.setViewportView(lbRossz);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(12, 208, 291, 99);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static DefaultListModel<DHaromszog> oldalak = new DefaultListModel<>();
    static DefaultListModel<String> hibak = new DefaultListModel<>();
    private void btnBeolvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeolvasActionPerformed
        feltolt();
    }//GEN-LAST:event_btnBeolvasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mind1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mind1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mind1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mind1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mind1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeolvas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lbJo;
    private javax.swing.JList lbRossz;
    // End of variables declaration//GEN-END:variables

    private void feltolt() {
        int sorszam = 1;
        File f = new File("haromszogek.txt");
        try {
            Scanner be = new Scanner(f, "iso-8859-2");
            while (be.hasNextLine()) {
                try {
                    DHaromszog dh = new DHaromszog(be.nextLine().replace(',', '.'));
                    oldalak.addElement(dh);
                    lbJo.setModel(oldalak);
                } catch (RosszSorrend | NemHaromszog | NemDerek ex) {
                    hibak.addElement(sorszam+". "+ex.toString());
                    lbRossz.setModel(hibak);
                }
                sorszam++;
            }
        } catch (FileNotFoundException ex) {
            System.out.println("Hiba: " + ex);
        }
    }
}
