/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApplication234;

import java.io.File;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author wuncs.david
 */
public class frmOrszagok extends javax.swing.JFrame {

    DefaultListModel<Orszag> orszagok = new DefaultListModel<>();
    static DefaultListModel <Orszag> euk =
            new DefaultListModel<>();
    public frmOrszagok() {
        initComponents();
        lbORszagok.setModel(orszagok);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbORszagok = new javax.swing.JList();
        rbTobb = new javax.swing.JRadioButton();
        rbKevesebb = new javax.swing.JRadioButton();
        btnCount = new javax.swing.JButton();
        tfCount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblMinimax = new javax.swing.JLabel();
        cbMinimax = new javax.swing.JComboBox();
        btnIr = new javax.swing.JButton();
        lblAvg = new javax.swing.JLabel();
        btnAvg = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mEur = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbORszagok.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lbORszagok);

        buttonGroup1.add(rbTobb);
        rbTobb.setSelected(true);
        rbTobb.setText("10 milliónál több");

        buttonGroup1.add(rbKevesebb);
        rbKevesebb.setText("Nem több mint 10 millió");

        btnCount.setText("Megszámol");
        btnCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountActionPerformed(evt);
            }
        });

        tfCount.setEditable(false);

        jLabel1.setText("legkisebb/legnagyobb népesség: ");

        cbMinimax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Legkisebb", "Legnagyobb" }));

        btnIr.setText("Kiír");
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });

        btnAvg.setText("Átlag");
        btnAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvgActionPerformed(evt);
            }
        });

        mFile.setText("File");
        mFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mFileMouseClicked(evt);
            }
        });
        mFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFileActionPerformed(evt);
            }
        });
        jMenuBar1.add(mFile);

        mEur.setText("Európai");
        mEur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mEurMouseClicked(evt);
            }
        });
        jMenuBar1.add(mEur);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbTobb)
                                    .addComponent(rbKevesebb)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnCount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(tfCount, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMinimax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblAvg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cbMinimax, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnIr, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(rbTobb)
                        .addGap(18, 18, 18)
                        .addComponent(rbKevesebb)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCount)
                            .addComponent(tfCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblMinimax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMinimax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAvg)))
                .addGap(18, 18, 18)
                .addComponent(btnAvg)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFileActionPerformed
       
    }//GEN-LAST:event_mFileActionPerformed

    private void mFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mFileMouseClicked
        JFileChooser fc = new JFileChooser();
        if (fc.showOpenDialog(this) == 0){
            beolvas(fc.getSelectedFile());
        }
    }//GEN-LAST:event_mFileMouseClicked

    private void btnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountActionPerformed
        tfCount.setText(szamol());
    }//GEN-LAST:event_btnCountActionPerformed

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        lblMinimax.setText(minmax(cbMinimax.getSelectedIndex()));
    }//GEN-LAST:event_btnIrActionPerformed

    private void btnAvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvgActionPerformed
        lblAvg.setText(atl());
    }//GEN-LAST:event_btnAvgActionPerformed

    private void mEurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mEurMouseClicked
        eu();
        frmEu fe = new frmEu();
        fe.setVisible(true);
    }//GEN-LAST:event_mEurMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOrszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOrszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOrszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOrszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOrszagok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvg;
    private javax.swing.JButton btnCount;
    private javax.swing.JButton btnIr;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbMinimax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lbORszagok;
    private javax.swing.JLabel lblAvg;
    private javax.swing.JLabel lblMinimax;
    private javax.swing.JMenu mEur;
    private javax.swing.JMenu mFile;
    private javax.swing.JRadioButton rbKevesebb;
    private javax.swing.JRadioButton rbTobb;
    private javax.swing.JTextField tfCount;
    // End of variables declaration//GEN-END:variables

    private void beolvas(File f) {
        try {
            Scanner be = new Scanner(f,"ISO-8859-2");
            while (be.hasNextLine()){
                orszagok.addElement(new Orszag (
                     be.nextLine(),
                     Integer.parseInt(be.nextLine()),
                     be.nextLine()));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private String szamol() {
        int t = 0;
        int k = 0;
        
        for (int i = 0; i < orszagok.size(); i++) {
            if (orszagok.get(i).nepe > 10000)
                t++;
            else
                k++;
        }
        if (rbTobb.isSelected())
            return t+"";
        else
            return k+"";
    }

    private String minmax(int index) {
        Orszag min = orszagok.get(0);
        Orszag max = orszagok.get(0);
        
        for (int i = 0; i < orszagok.size(); i++) {
            if (orszagok.get(i).nepe < min.nepe)
                min = orszagok.get(i);
            if (orszagok.get(i).nepe > max.nepe)
                max = orszagok.get(i);
        }
        
        if (index == 0)
            return min.nev;
        else
            return max.nev;
        
    }

    private String atl() {
        double avg = 0;
        for (int i = 0; i < orszagok.size(); i++) {
            avg += orszagok.get(i).nepe;
        }
        avg /= orszagok.size();
        return String.format("Átlag: %.2fe fõ.", avg);
    }

    private void eu() {
        for (int i = 0; i < orszagok.size(); i++) {
            if (orszagok.get(i).kont.equals("Európa"))
                euk.addElement(orszagok.get(i));
        }
    }
}
