/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1212_2425_14b_filechooser;

import java.awt.event.MouseEvent;
import java.io.File;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;

/**
 *
 * @author wuncs.david
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTest = new javax.swing.JButton();
        mbFile = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mItems = new javax.swing.JMenu();
        miItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        btnTest.setText("Teszt");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        mFile.setText("File");
        mFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mFileMouseClicked(evt);
            }
        });
        mFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFileActionPerformed(evt);
            }
        });
        mbFile.add(mFile);

        mItems.setText("Items");

        miItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miItem1.setText("Item");
        miItem1.setIconTextGap(2);
        miItem1.setPreferredSize(new java.awt.Dimension(171, 24));
        miItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miItem1ActionPerformed(evt);
            }
        });
        mItems.add(miItem1);

        mbFile.add(mItems);

        jMenu1.setText("Névjegy");
        mbFile.add(jMenu1);

        setJMenuBar(mbFile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miItem1ActionPerformed
        System.out.println("A");
    }//GEN-LAST:event_miItem1ActionPerformed

    private void mFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFileActionPerformed
//        JFileChooser fc = new JFileChooser();
//        fc.showOpenDialog(fc);
//        System.out.println("a");
    }//GEN-LAST:event_mFileActionPerformed
    int ret;
    private void mFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mFileMouseClicked
        JFileChooser fc = new JFileChooser();
        ret = fc.showOpenDialog(this);
        
        if (ret == 0){
//            System.out.println(fc.getSelectedFile());
//            System.out.println(fc.getSelectedFile().getAbsolutePath());
//            System.out.println(fc.getSelectedFile().getPath());
//            System.out.println(fc.getSelectedFile().getName());
            beolvas(fc.getSelectedFile());
        }
        
    }//GEN-LAST:event_mFileMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        System.out.println(SwingUtilities.isRightMouseButton(evt));
        System.out.println(evt.getClickCount());
    }//GEN-LAST:event_formMouseClicked

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
//        System.out.println(evt.getClickCount());
//        System.out.println(SwingUtilities.isRightMouseButton(evt));
    }//GEN-LAST:event_btnTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTest;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mItems;
    private javax.swing.JMenuBar mbFile;
    private javax.swing.JMenuItem miItem1;
    // End of variables declaration//GEN-END:variables

    private void beolvas(File sF) {
        try {
            Scanner be = new Scanner(sF,"UTF-8");
            String sor;
            String adatok [];
            
            while(be.hasNextLine()){
                sor = be.nextLine();
                adatok = sor.split(";");
                System.out.println(
                       Arrays.toString(adatok));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
