/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gy1013_2223_14a_kolcsonzes;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author wuncs.david
 */
public class frm_Bej extends javax.swing.JFrame {

    /**
     * Creates new form frm_Bej
     */
    public frm_Bej() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBelep = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mBeolvas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBelep.setText("Megnyit");
        btnBelep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBelepActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Kérem olvassa be a szükséges fájlokat!");
        jLabel1.setOpaque(true);

        mBeolvas.setText("Beolvas");
        mBeolvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mBeolvasMouseClicked(evt);
            }
        });
        jMenuBar1.add(mBeolvas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBelep, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnBelep, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    static JFileChooser fc = new JFileChooser();
    static DefaultListModel<Tulaj> szabad_tulajok =
            new DefaultListModel<>();
    static DefaultListModel<Tulaj> foglalt_tulajok =
            new DefaultListModel<>();
    static DefaultListModel<Cica> szabad_cicak =
            new DefaultListModel<>();
    static DefaultListModel<Cica> foglalt_cicak =
            new DefaultListModel<>();
    static String path_c;
    static String path_t;
    static File f;
    private void mBeolvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mBeolvasMouseClicked
        int er = fc.showOpenDialog(this);
        if ( er == JFileChooser.APPROVE_OPTION){
            f = fc.getSelectedFile();
            String s = f.getName();
            try{
                Scanner be = new Scanner(f,"UTF-8");
                if (s.equals("cicak.txt") || s.equals("Tulajok.csv")){
                    beolvas(be,s);
                    
                }
                else
                    JOptionPane.showMessageDialog(null,"Ez a fájl nem beolvasható");
            }
            catch (FileNotFoundException fnf){
                System.out.println(fnf);
            }
        }
    }//GEN-LAST:event_mBeolvasMouseClicked

    private void btnBelepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBelepActionPerformed
        if ((!szabad_tulajok.isEmpty() || 
             !foglalt_tulajok.isEmpty()) && 
            (!szabad_cicak.isEmpty() ||
             !foglalt_cicak.isEmpty())){
            frmAlap frm = new frmAlap();
            frm.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,
                    "Nincs beolvasva az összes fájl.");
        }
    }//GEN-LAST:event_btnBelepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Bej.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Bej.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Bej.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Bej.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Bej().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBelep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mBeolvas;
    // End of variables declaration//GEN-END:variables

    private void beolvas(Scanner be, String s) {
        be.nextLine();
        String sor;
        String [] adatok;
        if (s.equals("Tulajok.csv")){
            path_t = f.getPath();
            while (be.hasNextLine()){
                sor = be.nextLine();
                adatok = sor.split(";");
                Tulaj t = new Tulaj(
                adatok[0],
                Integer.parseInt(adatok[1]),
                adatok[2]);
                if (t.getTul().equals("Igen"))
                    foglalt_tulajok.addElement(t);
                else
                    szabad_tulajok.addElement(t);
                
            }
        }
        else{
            path_c = f.getPath();
            while (be.hasNextLine()){
                sor = be.nextLine();
                adatok = sor.split(";");
                Cica c = new Cica(
                adatok[0],
                Integer.parseInt(adatok[1]),
                adatok[2],adatok[3]);
                if (c.getFoglalt().equals("Nem"))
                    szabad_cicak.addElement(c);
                else
                    foglalt_cicak.addElement(c);
                
            }
        }
    }
}
