/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Orszagok;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Wuncs.David
 */
public class frmOrszagok extends javax.swing.JFrame {

    /**
     * Creates new form frmOrszagok
     */
    public frmOrszagok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbOrszagok = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        rbTobb = new javax.swing.JRadioButton();
        rbKevesebb = new javax.swing.JRadioButton();
        btnMegszamol = new javax.swing.JButton();
        tfMegszamol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbMinMax = new javax.swing.JComboBox();
        btnKiir = new javax.swing.JButton();
        btnAtlag = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        labelMinden = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miBeolvas = new javax.swing.JMenuItem();
        mEu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Országok Népessége");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ORSZÁGOK NÉPESSÉGE");

        jScrollPane1.setViewportView(lbOrszagok);

        jLabel2.setText("Mit számoljak?");

        rbTobb.setText("10 milliónál több");

        rbKevesebb.setText("Legfeljebb 10 millió");

        btnMegszamol.setText("Megszámol");

        jLabel3.setText("legnagyobb/legkisebb népesség");

        cbMinMax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Legnagyobb", "Legkisebb" }));

        btnKiir.setText("Kiíratás");

        btnAtlag.setText("Átlag népesség");

        btnExit.setText("Kilépés");

        labelMinden.setText("Itt lesz minden is kiírva");

        mFile.setText("File");

        miBeolvas.setText("Beolvas");
        miBeolvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBeolvasActionPerformed(evt);
            }
        });
        mFile.add(miBeolvas);

        jMenuBar1.add(mFile);

        mEu.setText("Európaiak");
        jMenuBar1.add(mEu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMegszamol)
                                .addGap(18, 18, 18)
                                .addComponent(tfMegszamol))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtlag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(btnExit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbKevesebb)
                                            .addComponent(rbTobb)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbMinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnKiir))
                                    .addComponent(labelMinden))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbTobb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbKevesebb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMegszamol)
                            .addComponent(tfMegszamol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKiir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMinden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtlag)
                            .addComponent(btnExit))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miBeolvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBeolvasActionPerformed
       feltolt();
       lbOrszagok.setModel(orszagok);
    }//GEN-LAST:event_miBeolvasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOrszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOrszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOrszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOrszagok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOrszagok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtlag;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnKiir;
    private javax.swing.JButton btnMegszamol;
    private javax.swing.JComboBox cbMinMax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMinden;
    private javax.swing.JList lbOrszagok;
    private javax.swing.JMenu mEu;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuItem miBeolvas;
    private javax.swing.JRadioButton rbKevesebb;
    private javax.swing.JRadioButton rbTobb;
    private javax.swing.JTextField tfMegszamol;
    // End of variables declaration//GEN-END:variables
    static DefaultListModel<Orszag> orszagok = new DefaultListModel<>();
    static DefaultListModel<Orszag> kisebb = new DefaultListModel<>();
    static DefaultListModel<Orszag> nagyobb = new DefaultListModel<>();
    static DefaultListModel<Orszag> euorszagok = new DefaultListModel<>();
    private void feltolt() {
        orszagok.clear();
        kisebb.clear();
        nagyobb.clear();
        euorszagok.clear();
        File f = new File("Orszagok.txt");
        try {
            Scanner be = new Scanner(f,"iso-8859-2");
            while(be.hasNextLine()){
                Orszag o = new Orszag(
                        be.nextLine(),
                        Integer.parseInt(be.nextLine()));
                if (o.getNepesseg()>10000)
                    nagyobb.addElement(o);
                else
                    kisebb.addElement(o);
                if (be.nextLine().equals("Európa"))
                    euorszagok.addElement(o);
                orszagok.addElement(o);
            }
        } catch (FileNotFoundException fnf) {
            System.out.println("Hiba: "+fnf);
        }
        
    }
}
